### ISSUE TITLE
Зачем нужен этот класс?

### ISSUE THREAD

**Issue by coursar** [Vi3arD/spring-course-task#1]
https://github.com/Vi3arD/spring-course-task/blob/bfff246d018eaca350eccf1b9250e66ede95a9b9/src/main/java/org/example/config/DataSource.java#L1-L11

**Comment by Vi3arD** [comment]
согласен, данный класс не нужен, забыл его удалить

**Comment by Vi3arD** [comment]
в такой реализации данный класс не нужен. Был переделан для использования для Annotation Configuration случая

**Comment by coursar** [comment]
Если "сделали" issue, то нужно закрывать его, желательно [коммитом](https://github.blog/2013-01-22-closing-issues-via-commit-messages/)

**Comment by Vi3arD** [comment]
хорошо, учту
