### ISSUE TITLE
Упростить Programmatic Config

### ISSUE THREAD

**Issue by coursar** [Vi3arD/spring-course-task#2]
https://github.com/Vi3arD/spring-course-task/blob/bfff246d018eaca350eccf1b9250e66ede95a9b9/src/test/java/ProgrammaticConfigTest.java#L27-L38

Нужно заменить весь этот код на два вызова:
```java
        context.registerBean("dataSource", ???);
        context.registerBean(ProgrammaticConfigPostgresConnector.class,
            ???, ???, ???
        );
```

Вместо ??? подставить значения

**Comment by Vi3arD** [comment]
@coursar при таком подходе не совсем понятно как подставить для PGSimpleDataSource 3-й параметр, который является бмном PGSimpleDataSource?

**Comment by coursar** [comment]
В подсказках написано посмотреть на интерфейс [`BeanReference`](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/beans/factory/config/BeanReference.html)

**Comment by Vi3arD** [comment]
поправил с учетом использования рекомендованного вами интерфейса
