### ISSUE TITLE
В AnnotationConfig получилась мешанина: сканируются и @Component и JavaConfig

### ISSUE THREAD

**Issue by coursar** [Vi3arD/spring-course-task#3]
https://github.com/Vi3arD/spring-course-task/blob/bfff246d018eaca350eccf1b9250e66ede95a9b9/src/test/java/AnnotationConfigTest.java#L11

Надо разнести так, чтобы `@Configuration` не подцеплялся.

**Comment by Vi3arD** [comment]
спасибо за замечание! поправил в последнем комите
